### ISSUE TITLE
Prevent adding company by users without authenticating 

### ISSUE THREAD

**Issue by JayjeetAtGithub** [arc9693/IntReview#12]
Currently , users can enter a company name without signing up. This should be prevented.

**Comment by kmAyush** [comment]
Started working on it. 
Should input for company name be disabled or disappear for user not signed up?

**Comment by JayjeetAtGithub** [comment]
You can make it behave similarly as in `https://archana9693.pythonanywhere.com/response/new` page.

**Comment by kmAyush** [comment]
Sorry, i didn't get you. I opened that provided link, i clicked on "Submit" then "Add a company" then added a company name and clicked "Upload" and its get added. I think that is the issue or am i getting wrong?

**Comment by JayjeetAtGithub** [comment]
@kmAyush  , Let me explain
When you will be clicking on the **Add a company button** , redirect to the login page if user is not logged in.
You should use the `@login_required` decorator for this purpose.
This guide will help you [Using Django Auth]( https://docs.djangoproject.com/en/2.1/topics/auth/default/)

**Comment by JayjeetAtGithub** [comment]
> Sorry, i didn't get you. I opened that provided link, i clicked on "Submit" then "Add a company" then added a company name and clicked "Upload" and its get added. I think that is the issue or am i getting wrong?

Yes , correct , thats the issue
