### ISSUE TITLE
UI/UX redesign

### ISSUE THREAD

**Issue by arc9693** [arc9693/IntReview#8]
The current UI does not look very attractive and can be designed in a better way.
### Suggestions:
- Use a solid theme.
- Replace background with gradient or a better vector.
- Add a section on landing page that explains the purpose of site.

#### Mock wireframe:
![screenshot from 2019-02-02 02-16-29](https://user-images.githubusercontent.com/36061892/52148825-e4f63e80-2690-11e9-8854-80004e25eaba.png)

**Comment by kmAyush** [comment]
working on this issue

**Comment by arc9693** [comment]
@kmAyush Keep me updated with your design on gitter.
